"""empty message

Revision ID: 1ae34902bb6f
Revises: None
Create Date: 2016-06-09 10:32:12.964301

"""

# revision identifiers, used by Alembic.
revision = '1ae34902bb6f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cell', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('notifications')
    ### end Alembic commands ###
