"""empty message

Revision ID: 62ea95c0c70b
Revises: dd2e3534efa8
Create Date: 2016-06-06 00:22:00.603826

"""

# revision identifiers, used by Alembic.
revision = '62ea95c0c70b'
down_revision = 'dd2e3534efa8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cell', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('accomodation', sa.Boolean(create_constraint=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cell', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('college', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('batch', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('branch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('accomodation', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.Column('special', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('users')
    ### end Alembic commands ###
