"""empty message

Revision ID: 847af053921e
Revises: 62ea95c0c70b
Create Date: 2016-06-08 00:10:37.196447

"""

# revision identifiers, used by Alembic.
revision = '847af053921e'
down_revision = '62ea95c0c70b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('username', 'users', ['username'], unique=True)
    ### end Alembic commands ###
