"""empty message

Revision ID: dd2e3534efa8
Revises: b7bf62a8011e
Create Date: 2016-06-05 13:41:12.398396

"""

# revision identifiers, used by Alembic.
revision = 'dd2e3534efa8'
down_revision = 'b7bf62a8011e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cell', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('accomodation', sa.Boolean(create_constraint=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('special', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
